name: CI-workflow.yml


on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]


jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - name: Lint check
        run: ruff check .

      - name: Format check
        run: ruff format --check .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --all-extras

      - name: Run mypy
        run: uv run mypy